### ISSUE TITLE
Suggestion: Module API divide JsSetModuleHostInfo

### ISSUE THREAD

**Issue by rhuanjl** [Microsoft/ChakraCore#5875]
```cc
JsSetModuleHostInfo(
    _In_ JsModuleRecord requestModule,
    _In_ JsModuleHostInfoKind moduleHostInfo,
    _In_ void* hostInfo)
```

**Currently JsSetModuleHostInfo is used for two fundamentally different types of thing**

1. It is used to set properties relating to an individual module, when setting any of these it is set onto the module record you pass in - these can be:
    i. an URL
    ii. host defined info
    iii. an exception
1. It is also used to setup the callbacks for module loading - these are set onto the script context (though the api uses GetScriptContext from the module record to know which context) these are:
    i. FetchImportedModuleCallback (used for child modules AND dynamic import from a module)
    ii. FetchImportedModuleFromScriptCallback (used for dynamic import from a script)
    iii. NotifyModuleReadyCallback (used to say a module is ready to execute)

**There are a few issues with this:**
1. It creates a potential for confusion - e.g. as the callbacks you set are actually set on the scriptContext but you're specifying a moduleRecord to set them on a user may think they need to set them each time they make a moduleRecord (which they don't) AND worse a user may think they can use a different callback for a different module in the same context - the latter one will override the first one and produce unexpected behaviour.

1. If an embedder wishes to setup dynamic import from scripts they have to create a throwaway module record to enable them to set the callbacks in advance.

1. If an embedder wishes to support only static import they either need a throwaway module record to set the callbacks in advance or they need to set them on their main entry point module OR they may (as ch actually does) unnecessarily set them every time a module record is created.

**Suggestion:**
1. Leave this API functioning as is so as not to break any existing implementations that use it.
1. Add a new additional API for setting the callbacks e.g. `JsSetModuleCallbacks` that takes the callback parameters and either also takes a JsContext parameter or internally uses GetCurrentContext. This api would therefore not require a moduleRecord parameter.
1. Update documentation to reccomend the use of this new api for setting callbacks and suggest JsSetModuleHostInfo just for the module specific info (URL, HostDefinedInfo and loading Exceptions)

**Note:**
As usual with any suggestion I make: If wanted I will open a PR to implement the suggestion.

**Comment by liminzhu** [comment]
Thanks for the suggestion! I think most of the confusion comes from the fact that you can set both per-module things AND per-context things (callbacks), which I agree is a little weird. 

My two cents - I do feel like this is a problem that can be easily solved with some documentation, plus there is something nice about having a single API for setting info. If the solution is to keep the current API + add new APIs + some clarification text in the current API, then I'd prefer just keeping the current ones and adding some clarification in the docs.

**Comment by rhuanjl** [comment]
@liminzhu thanks for the quick response, unpacking slightly on the second issue I mentioned above - setting up dynamic imports when module loading will then be done from script you have to do to following to set your callbacks:

```cc
JsModuleRecord throwAwayModule;
JsInitializeModuleRecord(NULL, throwAwaySpecifier, &throwAwayModule);
JsSetModuleHostInfo(throwAwayModule, JsModuleHostInfo_FetchImportedModuleCallback, on_fetch_imported_module);
JsSetModuleHostInfo(throwAwayModule, JsModuleHostInfo_FetchImportedModuleFromScriptCallback, on_fetch_dynamic_import);
JsSetModuleHostInfo(throwAwayModule, JsModuleHostInfo_NotifyModuleReadyCallback, on_notify_module_ready);
```

This feels awkward - and the only thing that throwAwayModule record is used for is providing a JsContext to the JsSetModuleHostInfo calls.

The reason I was saying new api + documentation and don't change the existing was to - avoid any possible breakage whilst also making a nicer and simpler to understand option.

**Alternative Idea**
Make the moduleRecord parameter optional when setting callbacks - change to:
```cc
JsSetModuleHostInfo(
    _In_opt_ JsModuleRecord requestModule,
    _In_ JsModuleHostInfoKind moduleHostInfo,
    _In_ void* hostInfo)
```
And alter the logic of the function such that it handles a nullptr requestModule if setting a callback.

**Comment by fatcerberus** [comment]
@liminzhu One issue with the current setup is you need a valid module record to set any of the callbacks — including the “dynamic import from script” callback which can be called *before any modules are loaded*.  This requires you to do `JsInitializeModuleRecord(NULL, NULL, &rec)` which isn’t 100% kosher (you can’t safely use that module record for anything other than as a gateway for setting the callbacks).

**Comment by fatcerberus** [comment]
Additional note: Any dynamic import will cause a segfault (nullptr dereference) if no callback is set—this being an actual issue I’ve hit in the past.

**Comment by rhuanjl** [comment]
The nullptr de-ref is kinda a different issue IMO - it's a minor bug that should be fixed but not really an API point (minor as you only hit if you forgot to set your callback).

**Comment by liminzhu** [comment]
@rhuanjl I really like the alternative idea. It basically relaxes the API shape without breaking anyone.
